apiVersion: v1
kind: Service
metadata:
  name: nginx-test-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx-test-deployment