name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # test_django_job:
  #   uses: codingforentrepreneurs/Django-Kubernetes/.github/workflows/test-django.yaml@main
  build:
    runs-on: ubuntu-latest
    # needs: [test_django_job]
    env:
      CLUSTER_NAME: django-k8s
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
      - name: Insall doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN_KEY }}
      - name: Login to DO Container Registry with short-lived creds
        run: doctl registry login --expiry-seconds 1200
      - name: Build container image
        working-directory: ./web
        run: |
          docker build -f Dockerfile \
            -t registry.digitalocean.com/ahmadmsvh-k8s/django-k8s-web:latest \
            -t registry.digitalocean.com/ahmadmsvh-k8s/django-k8s-web:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} \
            .
      - name: Push image
        run: |
          docker push registry.digitalocean.com/ahmadmsvh-k8s/django-k8s-web --all-tags
      - name: K8s cluster kubeconfig file with/ short-lived creds
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
      - name: Update deployment secrets
        run: |
          cat << EOF >> web/.env.prod
          AWS_ACCESS_KEY_ID=DO00GTVLHHTPDFC3DHVH
          AWS_SECRET_ACCESS_KEY=4u84V7J4oRRlwxe9AFp4j1DHH+vdrnx2EWB7oh4Eo0M
          DJANGO_SUPERUSER_USERNAME=admin
          DJANGO_SUPERUSER_PASSWORD=by62cwAjFRH2nx8Usxczv7gwE1fH6yaDfxWuNq0tfKY
          DJANGO_SUERPUSER_EMAIL=$ahmadmsvh@gmail.com
          DJANGO_SECRET_KEY=%2^m6t!zt9bq^)98_u2r!ppn2b3e$u2##a+gi%^9t(hsss!bvw
          ENV_ALLOWED_HOST=174.138.106.204
          POSTGRES_DB=defaultdb
          POSTGRES_PASSWORD=AVNS_zvpMM2HRBmPLTpV443f
          POSTGRES_USER=doadmin
          POSTGRES_HOST=private-django-k8s-db-postgres-do-user-13418256-0.c.db.ondigitalocean.com
          POSTGRES_PORT=25060
          EOF
          kubectl delete secret django-k8s-web-prod-env
          kubectl create secret generic django-k8s-web-prod-env --from-env-file=web/.env.prod
      - name: Update Deployment image
        run: |
          kubectl set image deployment/django-k8s-web-deployment django-k8s-web=registry.digitalocean.com/ahmadmsvh-k8s/django-k8s-web:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}
      - name: Wait for rollout to finish
        run: |
          kubectl rollout status deployment/django-k8s-web-deployment
      - name: Post-build Django Commands - Migrate / Collectstatic
        run: |
          export SINGLE_POD_NAME=$(kubectl get pod -l app=django-k8s-web-deployment -o jsonpath="{.items[0].metadata.name}")
          kubectl exec -it $SINGLE_POD_NAME -- bash /app/migrate.sh
          kubectl exec -it $SINGLE_POD_NAME -- bash /app/collectstatic.sh



          
 