name: nginx-doc Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: django-k8s
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
      - name: Insall doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN_KEY }}
      - name: Login to DO Container Registry with short-lived creds
        run: doctl registry login --expiry-seconds 1200
      - name: Build container image
        working-directory: k8s/nginx-test
        run: |
          docker build -f Dockerfile \
            -t registry.digitalocean.com/ahmadmsvh-k8s/nginx-doc:latest \
            -t registry.digitalocean.com/ahmadmsvh-k8s/nginx-doc:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} \
            .
      - name: Push image
        run: |
          docker push registry.digitalocean.com/ahmadmsvh-k8s/nginx-doc --all-tags
      - name: K8s cluster kubeconfig file with/ short-lived creds
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
      - name: Update Deployment image
        run: |
          kubectl set image deployment/nginx-test-deployment nginx-test=registry.digitalocean.com/ahmadmsvh-k8s/nginx-doc:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}
      - name: Wait for rollout to finish
        run: |
          kubectl rollout status deployment/nginx-test-deployment
